spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    com.example : DEBUG
kakao:
  client-id: 58eed44d11c6af52c6a68c04e0535346
  client-secret: bBPBGpVCVBztPXD2OW5HeBNtTUUNU5YY
  redirect-uri: http://localhost:8080/api/auth/login/kakao
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

naver:
  client-id: jzQ_Z_TqlmAVqPcgNCwr
  client-secret: eseJBAMxn2
  redirect-uri: http://localhost:8080/api/auth/login/naver
  token-uri: https://nid.naver.com/oauth2.0/token
  user-info-uri: https://openapi.naver.com/v1/nid/me